export const PATH = {
    HOME: '/',
    STORE: '/store',
    DEALER: '/dealer',
    BASE: '/base',
    PRODUCT: '/product',
    NEWS: '/news',
    CONTACT: '/contact',
    DASHBOARD: '/admin/dashboard',
    PROFILE: '/profile',
    ADMIN: '/admin',
    MANAGE_USER: '/admin/manage-user',
    MANAGE_PRODUCTS: '/admin/manage-products',
    ADD_PRODUCT: '/admin/manage-product/add-product',
    EDIT_PRODUCT: '/admin/manage-product/edit-product',
    DETAIL_PRODUCT: '/store/detail',
    CART: '/cart',
    CHECKOUT: '/checkout',
    PAYMENT_SUCCESS: '/payment-success',
    KOI_MANAGEMENT: '/koi-management',
    POND_MANAGEMENT: '/pond-management',
    WATER_PARAMETER: '/water-parameter',
    FOOD_CALCULATOR: '/food-calculator',
    SALT_CALCULATOR: '/salt-calculator'
}